name: Release

on:
  push:
    tags:
      - "v*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Get version
              id: get_version
              run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

            - name: Build
              uses: crazy-max/ghaction-xgo@v3
              with:
                  xgo_version: latest
                  go_version: 1.21
                  dest: build
                  targets: linux/arm64,linux/amd64,windows/amd64,darwin/amd64,darwin/arm64
                  v: false
                  x: false
                  race: false
                  ldflags: -s -w
                  buildmode: default
                  trimpath: true

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "v${{ steps.get_version.outputs.VERSION }}"
                  title: "Version ${{ steps.get_version.outputs.VERSION }}"
                  prerelease: false
                  files: |
                    build/github.com/zijiren233/livelib/*
